
import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class FlightScheduler extends javax.swing.JFrame {

    /**
     * Creates new form FlightScheduler
     */
    private String customer;
    private String flight="";
    private Date date;
    private Timestamp timestamp;
    private int seatCount=0;
    public FlightScheduler() {
        initComponents();
        bookFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
        statusFlightListComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
        statusDayDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
        SpinnerModel monthModel = new SpinnerDateModel();
        addDateSpinner.setModel(monthModel);
        addDateSpinner.setEditor(new JSpinner.DateEditor(addDateSpinner, "yyyy-MM-dd"));
        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Bookings.getallNames().toArray()));
        statusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Bookings.getallNames().toArray()));
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bookFlightComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dateComboBox = new javax.swing.JComboBox<>();
        bookSubmitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookCustomerTextField = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        statusFlightListComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusDayTextrea = new javax.swing.JTextArea();
        statusBookSubmitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        statusDayDateComboBox = new javax.swing.JComboBox<>();
        statusWaitlistButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        statusCustomerComboBox = new javax.swing.JComboBox<>();
        statusCustomerButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addFlightNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addSeatCountTextField = new javax.swing.JTextField();
        addNewFlightButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        addDateSpinner = new javax.swing.JSpinner();
        addNewDateButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        addTextArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cancelCustomerComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cancelDateComboBox = new javax.swing.JComboBox<>();
        cancelSubmitButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        cancelTextArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        dropFlightComboBox = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        dropFlightTextArea = new javax.swing.JTextArea();
        dropFlightButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 100));
        jLabel1.setText("Flight Scheduler");

        jLabel2.setText("Customer Name:");

        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Flight:");

        bookFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bookFlightComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Date:");

        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboBoxActionPerformed(evt);
            }
        });

        bookSubmitButton.setText("Submit");
        bookSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSubmitButtonActionPerformed(evt);
            }
        });

        bookCustomerTextField.setEditable(false);
        bookCustomerTextField.setColumns(20);
        bookCustomerTextField.setRows(5);
        jScrollPane1.setViewportView(bookCustomerTextField);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(bookSubmitButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bookFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(bookSubmitButton)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Book", jPanel1);

        statusFlightListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusFlightListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFlightListComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Flights:");

        statusDayTextrea.setColumns(20);
        statusDayTextrea.setRows(5);
        jScrollPane2.setViewportView(statusDayTextrea);

        statusBookSubmitButton.setText("Check Bookings");
        statusBookSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusBookSubmitButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Date:");

        statusDayDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        statusWaitlistButton.setText("Check Waitlist");
        statusWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusWaitlistButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Customer:");

        statusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusCustomerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCustomerComboBoxActionPerformed(evt);
            }
        });

        statusCustomerButton.setText("Check Customer");
        statusCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusDayDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusFlightListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(statusBookSubmitButton)
                                .addGap(23, 23, 23)
                                .addComponent(statusWaitlistButton)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(statusCustomerButton)
                                .addGap(0, 74, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(statusFlightListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(statusCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusDayDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusWaitlistButton)
                    .addComponent(statusBookSubmitButton)
                    .addComponent(statusCustomerButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status", jPanel2);

        jLabel8.setText("Add New Flight:");

        jLabel9.setText("Flight Name:");

        addFlightNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightNameTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Seat Count:");

        addSeatCountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSeatCountTextFieldActionPerformed(evt);
            }
        });

        addNewFlightButton.setText("Add New Flight");
        addNewFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewFlightButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Add New Date:");

        addNewDateButton.setText("Add New Date");
        addNewDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDateButtonActionPerformed(evt);
            }
        });

        addTextArea.setColumns(20);
        addTextArea.setRows(5);
        jScrollPane3.setViewportView(addTextArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addFlightNameTextField)
                            .addComponent(addSeatCountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(addNewFlightButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(addDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(addNewDateButton)
                        .addGap(93, 93, 93))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addFlightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addSeatCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewDateButton)
                    .addComponent(addNewFlightButton))
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(166, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(125, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Add", jPanel3);

        jLabel11.setText("Customer:");

        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Date:");

        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelSubmitButton.setText("Submit");
        cancelSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSubmitButtonActionPerformed(evt);
            }
        });

        cancelTextArea.setColumns(20);
        cancelTextArea.setRows(5);
        jScrollPane4.setViewportView(cancelTextArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(cancelSubmitButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(56, 56, 56)
                                .addComponent(cancelCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cancelCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cancelSubmitButton)
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(192, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Cancel", jPanel4);

        jLabel14.setText("Flight:");

        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dropFlightTextArea.setColumns(20);
        dropFlightTextArea.setRows(5);
        jScrollPane5.setViewportView(dropFlightTextArea);

        dropFlightButton.setText("Submit");
        dropFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14)
                        .addGap(66, 66, 66)
                        .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(dropFlightButton)))
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dropFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(125, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Drop", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSubmitButtonActionPerformed
        // TODO add your handling code here:
        flight=bookFlightComboBox.getSelectedItem().toString();
        date=Date.valueOf(dateComboBox.getSelectedItem().toString());
        customer=customerNameTextField.getText();
        timestamp=new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        if (Flights.getSeatCount(flight)>Bookings.getBookedSeatsCount(flight, date)){
            System.out.println(flight+", "+date);
            Bookings.insertBookings(customer, flight, date, timestamp);
            bookCustomerTextField.setText(customer+" was booked on flight "+flight+" on "+date);
        }
        else
        {
            
            Waitlist.insertWaitlist(customer, flight, date, timestamp);
            bookCustomerTextField.setText(customer+" was placed on the waitlist for flight "+flight+" on "+date);
        }
        statusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Bookings.getallNames().toArray()));
        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Bookings.getallNames().toArray()));
    }//GEN-LAST:event_bookSubmitButtonActionPerformed

    private void dateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboBoxActionPerformed
        // TODO add your handling code here:
        date=Date.valueOf(dateComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_dateComboBoxActionPerformed

    private void bookFlightComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightComboBoxActionPerformed
        // TODO add your handling code here:
        flight=bookFlightComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_bookFlightComboBoxActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
        customer=customerNameTextField.getText();
    }//GEN-LAST:event_customerNameTextFieldActionPerformed

    private void statusBookSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusBookSubmitButtonActionPerformed
        // TODO add your handling code here:
        flight=statusFlightListComboBox.getSelectedItem().toString();
        date=Date.valueOf(statusDayDateComboBox.getSelectedItem().toString());
        statusDayTextrea.setText("Bookings:" +System.lineSeparator()+System.lineSeparator()+Bookings.retrieveBookings(flight, date).toString());
    }//GEN-LAST:event_statusBookSubmitButtonActionPerformed

    private void statusFlightListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFlightListComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFlightListComboBoxActionPerformed

    private void statusWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusWaitlistButtonActionPerformed
        // TODO add your handling code here:
        flight=statusFlightListComboBox.getSelectedItem().toString();
        date=Date.valueOf(statusDayDateComboBox.getSelectedItem().toString());
        statusDayTextrea.setText("Waitlist:" +System.lineSeparator()+System.lineSeparator()+Waitlist.retrieveWaitlist(flight, date).toString());
    }//GEN-LAST:event_statusWaitlistButtonActionPerformed

    private void addFlightNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFlightNameTextFieldActionPerformed

    private void addSeatCountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSeatCountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSeatCountTextFieldActionPerformed

    private void addNewFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewFlightButtonActionPerformed
        // TODO add your handling code here:
        flight=addFlightNameTextField.getText();
        seatCount=Integer.parseInt(addSeatCountTextField.getText());
        Flights.addNewFlight(flight, seatCount);
        bookFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
        statusFlightListComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
        addTextArea.setText("Added the following new Flight: "+flight);
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
    }//GEN-LAST:event_addNewFlightButtonActionPerformed

    private void addNewDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDateButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd"); 
        String spinnerValue = formater.format(addDateSpinner.getValue()); 
        Date day = Date.valueOf(spinnerValue);
        Dates.addNewDate(day);
        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
        statusDayDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
        addTextArea.setText("Added the following new date: "+day.toString());
        
    }//GEN-LAST:event_addNewDateButtonActionPerformed

    private void cancelSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSubmitButtonActionPerformed
        // TODO add your handling code here:
        customer=cancelCustomerComboBox.getSelectedItem().toString();
        date=Date.valueOf(cancelDateComboBox.getSelectedItem().toString());
        ScheduleEntry entry=Bookings.isBooked(customer,date);
        if (Bookings.isBooked(customer,date)!=null){
            Bookings.deleteBooking(customer, date);
            ScheduleEntry entry2=Bookings.bookFromWaitlist(entry.getFlight(), date);  
            
            if (entry2!=null)
                cancelTextArea.setText("Deleted the booking of flight "+entry.getFlight()+ "on "+date+" for customer: "+customer+"\n and booked "+entry2.getCustomer()+" off of the waitlist");
            else
                cancelTextArea.setText("Deleted the booking of flight "+entry.getFlight()+ " on "+date+" for customer: "+customer);
        }
        else{
            Waitlist.deleteWaitlistEntry(customer, date);
            cancelTextArea.setText("Deleted " +customer+" from the waitlist "+ "on "+date);
        }
        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Bookings.getallNames().toArray()));
        statusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Bookings.getallNames().toArray()));
    }//GEN-LAST:event_cancelSubmitButtonActionPerformed

    private void statusCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCustomerButtonActionPerformed
        // TODO add your handling code here:
        customer=statusCustomerComboBox.getSelectedItem().toString();
        statusDayTextrea.setText("Bookings for: "+customer +System.lineSeparator()+System.lineSeparator()+
                Bookings.retrieveBookingsByCustomer(customer).toString()+System.lineSeparator()+System.lineSeparator()+"Waitlist for: "+customer+System.lineSeparator()+System.lineSeparator()+
                Waitlist.retrieveWaitlistByCustomer(customer).toString());
        
    }//GEN-LAST:event_statusCustomerButtonActionPerformed

    private void statusCustomerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCustomerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusCustomerComboBoxActionPerformed

    private void dropFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFlightButtonActionPerformed
        // TODO add your handling code here:
        flight=dropFlightComboBox.getSelectedItem().toString();
        Flights.deleteFlight(flight);
        ArrayList<String> rebooked=Bookings.reBook(flight);
        ArrayList<String> waitlistDeletes=Waitlist.deleteWaitlistForFlight(flight);
        dropFlightTextArea.setText(rebooked.toString()+System.lineSeparator()+System.lineSeparator());
        dropFlightTextArea.append(waitlistDeletes.toString());
        
        bookFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
        statusFlightListComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Bookings.getallNames().toArray()));
        statusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Bookings.getallNames().toArray()));
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlightNames().toArray()));
        
        
    }//GEN-LAST:event_dropFlightButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightScheduler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner addDateSpinner;
    private javax.swing.JTextField addFlightNameTextField;
    private javax.swing.JButton addNewDateButton;
    private javax.swing.JButton addNewFlightButton;
    private javax.swing.JTextField addSeatCountTextField;
    private javax.swing.JTextArea addTextArea;
    private javax.swing.JTextArea bookCustomerTextField;
    private javax.swing.JComboBox<String> bookFlightComboBox;
    private javax.swing.JButton bookSubmitButton;
    private javax.swing.JComboBox<String> cancelCustomerComboBox;
    private javax.swing.JComboBox<String> cancelDateComboBox;
    private javax.swing.JButton cancelSubmitButton;
    private javax.swing.JTextArea cancelTextArea;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JButton dropFlightButton;
    private javax.swing.JComboBox<String> dropFlightComboBox;
    private javax.swing.JTextArea dropFlightTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton statusBookSubmitButton;
    private javax.swing.JButton statusCustomerButton;
    private javax.swing.JComboBox<String> statusCustomerComboBox;
    private javax.swing.JComboBox<String> statusDayDateComboBox;
    private javax.swing.JTextArea statusDayTextrea;
    private javax.swing.JComboBox<String> statusFlightListComboBox;
    private javax.swing.JButton statusWaitlistButton;
    // End of variables declaration//GEN-END:variables
}
